name: code-check
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'LIEF branch'
        default: master
        required: false
        type: string
      what:
        description: 'clang-tidy action'
        default: latest
        required: false
        type: string
      job:
        description: 'Job (e.g. coverage)'
        default: "all"
        required: false
        type: string
  push:
    branches:
      - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: liefproject/code-check
      env:
        LIEF_S3_KEY: ${{ secrets.LIEF_S3_KEY }}
        LIEF_S3_SECRET: ${{ secrets.LIEF_S3_SECRET }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lief-project/code-check
          token: ${{ secrets.LIEF_CLONE_TOKEN }}
      - name: Running LIEF coverage [workflow dispatch]
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.job == 'all' ||  github.event.inputs.job == 'coverage') }}
        run: ./lief-coverage --debug
      - name: Running LIEF coverage [regular]
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: ./lief-coverage --debug
  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: liefproject/code-check
      env:
        LIEF_S3_KEY: ${{ secrets.LIEF_S3_KEY }}
        LIEF_S3_SECRET: ${{ secrets.LIEF_S3_SECRET }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lief-project/code-check
          token: ${{ secrets.LIEF_CLONE_TOKEN }}
      - name: Running LIEF coverage [workflow dispatch]
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.job == 'all' ||  github.event.inputs.job == 'clang-tidy') }}
        run: ./lief-tidy --branch ${{ github.event.inputs.branch }} ${{ github.event.inputs.what }}
      - name: Running LIEF coverage [regular]
        if: "github.event.name != 'workflow_dispatch'"
        run: ./lief-tidy latest
  memory-profiler:
    runs-on: ubuntu-latest
    container:
      image: liefproject/code-check
      env:
        LIEF_S3_KEY: ${{ secrets.LIEF_S3_KEY }}
        LIEF_S3_SECRET: ${{ secrets.LIEF_S3_SECRET }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lief-project/code-check
          token: ${{ secrets.LIEF_CLONE_TOKEN }}
      - name: Running LIEF memory profiler [workflow dispatch]
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.job == 'all' ||  github.event.inputs.job == 'memprof') }}
        run: ./lief-memory-profile --branch ${{ github.event.inputs.branch }}
      - name: Running LIEF memory profiler [regular]
        if: "github.event.name != 'workflow_dispatch'"
        run: ./lief-memory-profile
