name: 'macOS-arm64'
on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  osx-sdk:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install system dependencies
        run: |
          brew install cmake ninja ccache
          python -m pip install --upgrade pip setuptools wheel
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m-%d-%H;%M;%S")"
        shell: bash
      - name: Setup cache dir
        shell: bash
        run: |
          mkdir -p ~/.ccache
      - name: ccache cache files
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: osx-${{ runner.os }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
              osx-${{ runner.os }}-
      - name: Upgrade pip
        shell: bash
        run: |
          python -m pip install --upgrade pip setuptools
      - name: Build SDK
        shell: bash
        env:
          MACOSX_DEPLOYMENT_TARGET: "11.0"
          CCACHE_DIR: ~/.ccache
          CCACHE_MAXSIZE: 10.0G
          CCACHE_CPP2: 1
          CCACHE_COMPRESS: 1
        run: |
          bash scripts/osx/package_sdk_aarch64.sh
      - name: 'Upload SDK Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: osx-sdk
          path: build/*.tar.gz
          retention-days: 3
      - name: Deploy
        env:
          LIEF_S3_KEY: ${{ secrets.LIEF_S3_KEY }}
          LIEF_S3_SECRET: ${{ secrets.LIEF_S3_SECRET }}
        shell: bash
        run: |
          python -m pip install --upgrade requests mako boto3
          python .github/deploy.py
