name: LIEF PR

on: [pull_request, workflow_dispatch]

jobs:
  osx:
    runs-on: macos-11.0
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: |
          brew install cmake ninja ccache
          python -m pip install --upgrade pip setuptools wheel
      - name: Build with Python ${{ matrix.python-version }} & Test
        shell: bash
        env:
          LIEF_SAMPLES_DIR: "/tmp/samples"
        run: |
          python -m pip install pytest requests
          python tests/dl_samples.py ${LIEF_SAMPLES_DIR}
          python -m pip -vv install api/python
          python ./tests/run_pytest.py
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build & Test
        shell: bash
        env:
          PYTHON_VERSION: 39
        run: |
          docker run --rm \
           -e PYTHON_VERSION=$PYTHON_VERSION \
           -e PYTHON_BINARY=/opt/python/cp39-cp39/bin/python3.9 \
           -v $GITHUB_WORKSPACE:/src \
           liefproject/manylinux_2_28_x86_64 bash /src/scripts/docker/run_linux_test.sh
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install system dependencies
      run: |
        choco install ninja
        python -m pip install --upgrade pip setuptools
        python -m pip install wheel mako
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: "14.16"
    - name: Set env variables
      run: |
        chcp 65001 #set code page to utf-8
        echo ("LIEF_SAMPLES_DIR=" + $env:RUNNER_TEMP + "/samples") >> $env:GITHUB_ENV
    - name: Build and Test
      run: |
        python -m pip install pytest requests
        python tests/dl_samples.py %LIEF_SAMPLES_DIR%
        python -m pip -vv install api/python
        python ./tests/run_pytest.py
      shell: cmd


